### PR TITLE
Fix camelCase names and abstract functions

### PR DESCRIPTION
**Pull request by sutem**
Fixed folding cameCase of function name and abstract functions.

### CODE REVIEW

**Comment by rayburgemeestre** [comment]
Looks good to me, Thanks! :)

**Comment by mikehaertl** [comment]
@rayburgemeestre I know this is bad practice but you disabled issues in this repo, so I have to ask here.

I'm not sure if it's related to this fix, but it seems that folding of abstract functions is somehow broken. Here's a quick example:

```php
<?php
<?php
abstract class X
{
    abstract public static function a();

    public function b()
    {
    }
}
```

For me the first fold of abstract function "sallows" the following `b()` function:

```
abstract class X                                                                                                                                  
{                                                                                                                                                 
+--  5 lines: abstract public static function a();································································································
}
```

Any idea?

**Comment by sutem** [comment]
Try adding phpDoc description for public function b and rebuild folds :EnableFastPHPFolds)

**Comment by mikehaertl** [comment]
@sutem Thanks for the quick response!

In my actual code there *is* a docblock - same problem. Calling `:EnableFastPHPFolds` makes no difference.

**Comment by mikehaertl** [comment]
@sutem Can you reproduce the issue?

I tried to play around and commented out the line you added. It makes no difference at all. Even without your change, the problem persists.

I found that it creates a nested fold: at level 1 is function a + b. Inside that is another fold at level 2 that only contains function b.

**Comment by mikehaertl** [comment]
@sutem I've provided a fix that improves the existing regex. Especially the regex for functions was not very good.

**Comment by rayburgemeestre** [comment]
Hi @mikehaertl & @sutem 
no problem, I wasn't aware of issues not being enabled on github. I guess I never enabled the checkbox. Fixed that now.
I see you created a PR, awesome, tnx for the contribution!

**Pull request merged**
